### ISSUE TITLE
Management portal regression

### ISSUE THREAD

**Issue by Gillingham** [docker-library/rabbitmq#96]
I just upgraded to the current :management image and now the management portal no longer works,
```
curl https://127.0.0.1:15671
curl: (56) Recv failure: Connection reset by peer
```

Looking at the docker logs, I see 
```
=INFO REPORT==== 7-Jul-2016::21:31:51 ===
started SSL Listener on [::]:5671

=INFO REPORT==== 7-Jul-2016::21:31:51 ===
Management plugin started. Port: 15672
```

Seems in the recent configuration refactor the management plugin configuration got broken from running on the SSL port, 15671 to match the ssl rabbitmq port of 5671

**Comment by Gillingham** [comment]
Looks like the generated config is invalid or not being read to configure the management portal correctly:
```
docker exec -i -t *container* cat /etc/rabbitmq/rabbitmq.config
[ { rabbit, [
	{ loopback_users, [ ] },
	{ tcp_listeners, [ ] },
	{ ssl_listeners, [ 5671 ] },
	{ ssl_options, [
		{ fail_if_no_peer_cert, true },
		{ verify, verify_peer },
		{ cacertfile, "/etc/rabbitmq/rabbitmqCA.crt" },
		{ certfile, "/etc/rabbitmq/rabbitmq.crt" },
		{ keyfile, "/etc/rabbitmq/rabbitmq.key" }
	] },
	{ default_pass, <<"********">> },
	{ default_user, <<"********">> },
	{ hipe_compile, false },
	{ rabbitmq_management, [ { listener, [
		{ port, 15671 },
		{ ssl, true },
		{ ssl_opts, [
			{ fail_if_no_peer_cert, true },
			{ verify, verify_peer },
			{ cacertfile, "/etc/rabbitmq/rabbitmqCA.crt" },
			{ certfile, "/etc/rabbitmq/rabbitmq.crt" },
			{ keyfile, "/etc/rabbitmq/rabbitmq.key" }
		] }
	] } ] }
] } ].
```

```
docker exec -i -t *container* curl -I http://localhost:15672
HTTP/1.1 200 OK
```

**Comment by tianon** [comment]
Arg, thanks for pointing this out!  Looks like I put `rabbitmq_management` one level too deep!  Will have a fix pushed in just another moment!

**Comment by donnex** [comment]
I'm having the same problem. Thanks for a fast fix :)

**Comment by Gillingham** [comment]
@tianon thanks for the rapid fix, but there's still an issue here in that prior the management portal always had: 
```
      { verify,   verify_none },
      { fail_if_no_peer_cert, false }
```
With the new config generator it gets set to the same verify/fail_if_no_peer_cert settings that the aqmp port uses, which in my case, is undesirable since I'm proxying to the port via an actual web server to expose it behind authentication.

**Comment by tianon** [comment]
Oh shoot, I see.  Different defaults.  :disappointed:

Not sure how to reconcile that in the UX. :confused:

**Comment by Gillingham** [comment]
I think leaving the legacy settings would be appropriate, since this change breaks existing behavior. I somewhat assume I'm not the only one that is proxying the rabbitmq management portal behind some other web proxy/server.

I also don't really see too much of a use case for the web management portal to use peer validation of certificates. To take advantage of that you would have to generate certificates and install them in whatever browser(s) you wanted to view the management portal in. Though I am impressed it does seem to function in some testing via curl.
```
curl -ik https://127.0.0.1:15671
curl: (35) NSS: client certificate not found (nickname not specified)

curl -ik --key test.key --cert test.crt https://127.0.0.1:15671
HTTP/1.1 200 OK
```
